# Further analysis

Here we would like to analyze the combined training data, and set up a recurrent framework.

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import missingno as msno
import matplotlib.pyplot as plt


sns.set_style("whitegrid")

Notice that to combine the three tables, train_clinical, train_peptide and train_protein, the most convenient way is to pivot the later two table.

In [ ]:
clinical=pd.read_csv("../Data/train_clinical_data.csv")
peptides=pd.read_csv("../Data/train_peptides.csv")
proteins=pd.read_csv("../Data/train_proteins.csv")

In [ ]:
# Note that visit_id is a concatenation of both patient_id and visit_month, so it is enough to just keep that
peptides_pivotted=peptides.pivot(columns="Peptide", index="visit_id", values="PeptideAbundance")
peptides_pivotted=peptides_pivotted.reset_index()
peptides_pivotted.head(5)

Peptide,visit_id,AADDTWEPFASGK,AAFGQGSGPIMLDEVQC(UniMod_4)TGTEASLADC(UniMod_4)K,AAFTEC(UniMod_4)C(UniMod_4)QAADK,AANEVSSADVK,AATGEC(UniMod_4)TATVGKR,AATVGSLAGQPLQER,AAVYHHFISDGVR,ADDKETC(UniMod_4)FAEEGK,ADDKETC(UniMod_4)FAEEGKK,...,YSLTYIYTGLSK,YTTEIIK,YVGGQEHFAHLLILR,YVM(UniMod_35)LPVADQDQC(UniMod_4)IR,YVMLPVADQDQC(UniMod_4)IR,YVNKEIQNAVNGVK,YWGVASFLQK,YYC(UniMod_4)FQGNQFLR,YYTYLIMNK,YYWGGQYTWDMAK
0,10053_0,6580710.0,31204.4,7735070.0,NaN,NaN,NaN,46620.3,236144.0,NaN,...,202274.0,NaN,4401830.0,77482.6,583075.0,76705.7,104260.0,530223.0,NaN,7207.30
1,10053_12,6333510.0,52277.6,5394390.0,NaN,NaN,NaN,57554.5,108298.0,45885.4,...,201009.0,NaN,5001750.0,36745.3,355643.0,92078.1,123254.0,453883.0,49281.9,25332.80
2,10053_18,7129640.0,61522.0,7011920.0,35984.7,17188.0,19787.3,36029.4,708729.0,5067790.0,...,220728.0,NaN,5424380.0,39016.0,496021.0,63203.6,128336.0,447505.0,52389.1,21235.70
3,10138_12,7404780.0,46107.2,10610900.0,NaN,20910.2,66662.3,55253.9,79575.5,6201210.0,...,188362.0,9433.71,3900280.0,48210.3,328482.0,89822.1,129964.0,552232.0,65657.8,9876.98
4,10138_24,13788300.0,56910.3,6906160.0,13785.5,11004.2,63672.7,36819.8,34160.9,2117430.0,...,206187.0,6365.15,3521800.0,69984.6,496737.0,80919.3,111799.0,NaN,56977.6,4903.09

In [ ]:
proteins_pivotted=proteins.pivot(columns="UniProt", index="visit_id", values="NPX")
proteins_pivotted=peptides_pivotted.reset_index()
proteins_pivotted.head(5)

Peptide,index,visit_id,AADDTWEPFASGK,AAFGQGSGPIMLDEVQC(UniMod_4)TGTEASLADC(UniMod_4)K,AAFTEC(UniMod_4)C(UniMod_4)QAADK,AANEVSSADVK,AATGEC(UniMod_4)TATVGKR,AATVGSLAGQPLQER,AAVYHHFISDGVR,ADDKETC(UniMod_4)FAEEGK,...,YSLTYIYTGLSK,YTTEIIK,YVGGQEHFAHLLILR,YVM(UniMod_35)LPVADQDQC(UniMod_4)IR,YVMLPVADQDQC(UniMod_4)IR,YVNKEIQNAVNGVK,YWGVASFLQK,YYC(UniMod_4)FQGNQFLR,YYTYLIMNK,YYWGGQYTWDMAK
0,0,10053_0,6580710.0,31204.4,7735070.0,NaN,NaN,NaN,46620.3,236144.0,...,202274.0,NaN,4401830.0,77482.6,583075.0,76705.7,104260.0,530223.0,NaN,7207.30
1,1,10053_12,6333510.0,52277.6,5394390.0,NaN,NaN,NaN,57554.5,108298.0,...,201009.0,NaN,5001750.0,36745.3,355643.0,92078.1,123254.0,453883.0,49281.9,25332.80
2,2,10053_18,7129640.0,61522.0,7011920.0,35984.7,17188.0,19787.3,36029.4,708729.0,...,220728.0,NaN,5424380.0,39016.0,496021.0,63203.6,128336.0,447505.0,52389.1,21235.70
3,3,10138_12,7404780.0,46107.2,10610900.0,NaN,20910.2,66662.3,55253.9,79575.5,...,188362.0,9433.71,3900280.0,48210.3,328482.0,89822.1,129964.0,552232.0,65657.8,9876.98
4,4,10138_24,13788300.0,56910.3,6906160.0,13785.5,11004.2,63672.7,36819.8,34160.9,...,206187.0,6365.15,3521800.0,69984.6,496737.0,80919.3,111799.0,NaN,56977.6,4903.09

In [ ]:
pivotted_peptides_and_protein=peptides_pivotted.merge(proteins_pivotted, on="visit_id", how="outer")
pivotted_peptides_and_protein.head(5)

Peptide,visit_id,AADDTWEPFASGK_x,AAFGQGSGPIMLDEVQC(UniMod_4)TGTEASLADC(UniMod_4)K_x,AAFTEC(UniMod_4)C(UniMod_4)QAADK_x,AANEVSSADVK_x,AATGEC(UniMod_4)TATVGKR_x,AATVGSLAGQPLQER_x,AAVYHHFISDGVR_x,ADDKETC(UniMod_4)FAEEGK_x,ADDKETC(UniMod_4)FAEEGKK_x,...,YSLTYIYTGLSK_y,YTTEIIK_y,YVGGQEHFAHLLILR_y,YVM(UniMod_35)LPVADQDQC(UniMod_4)IR_y,YVMLPVADQDQC(UniMod_4)IR_y,YVNKEIQNAVNGVK_y,YWGVASFLQK_y,YYC(UniMod_4)FQGNQFLR_y,YYTYLIMNK_y,YYWGGQYTWDMAK_y
0,10053_0,6580710.0,31204.4,7735070.0,NaN,NaN,NaN,46620.3,236144.0,NaN,...,202274.0,NaN,4401830.0,77482.6,583075.0,76705.7,104260.0,530223.0,NaN,7207.30
1,10053_12,6333510.0,52277.6,5394390.0,NaN,NaN,NaN,57554.5,108298.0,45885.4,...,201009.0,NaN,5001750.0,36745.3,355643.0,92078.1,123254.0,453883.0,49281.9,25332.80
2,10053_18,7129640.0,61522.0,7011920.0,35984.7,17188.0,19787.3,36029.4,708729.0,5067790.0,...,220728.0,NaN,5424380.0,39016.0,496021.0,63203.6,128336.0,447505.0,52389.1,21235.70
3,10138_12,7404780.0,46107.2,10610900.0,NaN,20910.2,66662.3,55253.9,79575.5,6201210.0,...,188362.0,9433.71,3900280.0,48210.3,328482.0,89822.1,129964.0,552232.0,65657.8,9876.98
4,10138_24,13788300.0,56910.3,6906160.0,13785.5,11004.2,63672.7,36819.8,34160.9,2117430.0,...,206187.0,6365.15,3521800.0,69984.6,496737.0,80919.3,111799.0,NaN,56977.6,4903.09

In [ ]:
clinical_and_pivotted_peptides_and_protein=pivotted_peptides_and_protein.merge(clinical, on="visit_id", how="outer")
clinical_and_pivotted_peptides_and_protein.head(80)

,visit_id,AADDTWEPFASGK_x,AAFGQGSGPIMLDEVQC(UniMod_4)TGTEASLADC(UniMod_4)K_x,AAFTEC(UniMod_4)C(UniMod_4)QAADK_x,AANEVSSADVK_x,AATGEC(UniMod_4)TATVGKR_x,AATVGSLAGQPLQER_x,AAVYHHFISDGVR_x,ADDKETC(UniMod_4)FAEEGK_x,ADDKETC(UniMod_4)FAEEGKK_x,...,YYC(UniMod_4)FQGNQFLR_y,YYTYLIMNK_y,YYWGGQYTWDMAK_y,patient_id,visit_month,updrs_1,updrs_2,updrs_3,updrs_4,upd23b_clinical_state_on_medication
0,10053_0,6580710.0,31204.4,7735070.0,NaN,NaN,NaN,46620.3,236144.0,NaN,...,530223.0,NaN,7207.3,10053.0,0.0,3.0,0.0,13.0,0.0,NaN
1,10053_12,6333510.0,52277.6,5394390.0,NaN,NaN,NaN,57554.5,108298.0,45885.4,...,453883.0,49281.9,25332.8,10053.0,12.0,4.0,2.0,8.0,0.0,NaN
2,10053_18,7129640.0,61522.0,7011920.0,35984.7,17188.0,19787.3,36029.4,708729.0,5067790.0,...,447505.0,52389.1,21235.7,10053.0,18.0,2.0,2.0,0.0,0.0,NaN
3,10053_24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,10053.0,24.0,4.0,3.0,0.0,0.0,NaN
4,10053_6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,10053.0,6.0,2.0,4.0,5.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,11686_60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,11686.0,60.0,2.0,0.0,1.0,NaN,NaN
76,11686_84,9812280.0,69997.9,9128540.0,32673.0,18331.4,NaN,37451.3,436173.0,4836650.0,...,477134.0,41560.0,36394.0,11686.0,84.0,3.0,0.0,2.0,NaN,NaN
77,11686_96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,11686.0,96.0,5.0,1.0,0.0,NaN,NaN
78,11928_0,5113420.0,41585.3,2303730.0,NaN,NaN,85583.3,69269.6,67441.2,9465620.0,...,NaN,NaN,46134.2,11928.0,0.0,2.0,2.0,14.0,NaN,NaN
79,11928_12,5942190.0,40317.0,12220000.0,22596.9,14567.7,71842.3,56117.9,530845.0,12719200.0,...,509054.0,63972.8,23097.1,11928.0,12.0,3.0,4.0,19.0,NaN,NaN

Observe that there are some cases when a patient took the peptide and protein test but didn't take the updrs score test, drop them for now.

In [ ]:
print(f"there are {clinical_and_pivotted_peptides_and_protein['visit_month'].isna().sum()} patient who took the peptide and protein test but didn't take the updrs score test")
display(clinical_and_pivotted_peptides_and_protein[clinical_and_pivotted_peptides_and_protein['visit_month'].isna()])
clinical_and_pivotted_peptides_and_protein_drop_untested=clinical_and_pivotted_peptides_and_protein.dropna(subset=['visit_month'])

there are 45 patient who took the peptide and protein test but didn't take the updrs score test

,visit_id,AADDTWEPFASGK_x,AAFGQGSGPIMLDEVQC(UniMod_4)TGTEASLADC(UniMod_4)K_x,AAFTEC(UniMod_4)C(UniMod_4)QAADK_x,AANEVSSADVK_x,AATGEC(UniMod_4)TATVGKR_x,AATVGSLAGQPLQER_x,AAVYHHFISDGVR_x,ADDKETC(UniMod_4)FAEEGK_x,ADDKETC(UniMod_4)FAEEGKK_x,...,YYC(UniMod_4)FQGNQFLR_y,YYTYLIMNK_y,YYWGGQYTWDMAK_y,patient_id,visit_month,updrs_1,updrs_2,updrs_3,updrs_4,upd23b_clinical_state_on_medication
74,11686_6,11325500.0,63127.90,7556900.0,35169.000,16050.200,NaN,36280.0,436531.0,4123890.0,...,488955.0,44630.0,16124.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
109,12636_6,7053890.0,7923.89,4928420.0,12736.700,NaN,57734.9,NaN,295976.0,2619950.0,...,436178.0,28616.2,4033.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,12703_108,5060310.0,57069.50,4403600.0,26237.500,2017.370,108172.0,NaN,275486.0,2301210.0,...,476673.0,39807.5,30967.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN
223,13968_6,5048160.0,69232.80,5773080.0,18715.200,627.006,38577.9,35505.0,68332.0,4252570.0,...,450303.0,33200.8,27553.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
229,14035_6,4493520.0,42678.20,6872460.0,NaN,NaN,35965.6,41708.1,342511.0,5117410.0,...,495339.0,39108.0,27860.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
279,14450_6,3444250.0,71386.10,2192220.0,45383.200,18042.500,110577.0,NaN,521732.0,3461160.0,...,73098.6,33680.7,21024.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
360,16347_6,4991850.0,60041.40,6100080.0,23726.200,3984.460,56594.9,33204.7,363078.0,5092880.0,...,392832.0,38910.2,29917.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN
533,20212_6,7997880.0,48308.80,6508820.0,60152.700,14103.000,113208.0,54063.3,30217.8,5357820.0,...,350231.0,61235.1,13797.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN
542,20216_6,7362740.0,54680.20,9865080.0,24689.600,6902.660,66164.4,44277.4,491551.0,5725490.0,...,488018.0,53923.0,24475.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN
593,20581_6,4364600.0,51033.50,11655800.0,25431.500,15084.500,89538.2,49365.6,504598.0,4909790.0,...,154505.0,48365.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
626,20791_6,8941610.0,65897.00,6523140.0,25767.300,8693.410,129402.0,NaN,412116.0,3783030.0,...,688805.0,48941.3,14966.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN
694,23175_3,5343910.0,45867.60,9499270.0,21460.300,12960.900,121481.0,38147.4,43468.3,3556290.0,...,422000.0,42278.6,19729.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN
697,23175_6,9203170.0,27577.20,6785320.0,27914.000,12060.000,102907.0,38615.2,366442.0,4131040.0,...,562550.0,44683.0,12323.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN
705,23192_6,4194450.0,30153.10,14906700.0,16639.500,14642.700,41907.6,72481.0,129674.0,5224680.0,...,399599.0,59867.0,62512.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN
744,24278_6,4290650.0,45622.50,9347460.0,20267.200,10677.500,179194.0,33866.0,43866.3,2846740.0,...,343526.0,26102.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
760,24818_6,7016960.0,94797.30,4238080.0,26664.500,739.917,161616.0,56044.3,58384.1,3462020.0,...,235307.0,59697.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
834,26005_48,5362720.0,68500.70,8457470.0,15525.100,11109.900,95499.4,53956.4,404565.0,4656980.0,...,455972.0,54950.1,46164.70,NaN,NaN,NaN,NaN,NaN,NaN,NaN
872,2660_6,6495700.0,12329.10,4177850.0,36261.800,9694.020,114595.0,NaN,382145.0,5154460.0,...,375290.0,35205.8,26996.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN
907,27300_6,7020290.0,39712.50,7930750.0,16670.800,13897.800,NaN,32073.9,50133.5,4826700.0,...,464983.0,36401.9,21030.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN
951,27715_36,5926290.0,59909.40,6857760.0,43553.400,14207.300,138184.0,49726.5,385258.0,3897600.0,...,391096.0,69337.8,15145.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1088,30894_6,7489210.0,40668.60,10870200.0,26846.800,23341.500,46570.4,46213.2,631982.0,6002620.0,...,608897.0,55262.5,28656.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1150,33108_6,12732900.0,44954.60,12723700.0,25571.900,NaN,55050.1,55636.3,548769.0,6723520.0,...,775605.0,86470.1,26367.90,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1214,35477_6,5977100.0,52585.60,7322800.0,27203.600,11911.100,53185.9,42535.9,50101.6,6173970.0,...,408848.0,43698.7,14258.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1309,39144_6,6172080.0,32908.40,5259930.0,19164.600,10390.300,67392.2,44182.3,403755.0,3418270.0,...,441011.0,43792.9,18653.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1450,41617_6,8407310.0,50508.30,9839650.0,45146.300,18837.000,97180.3,45041.9,47948.5,6127970.0,...,501019.0,54426.7,19507.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1471,41628_6,4837220.0,24149.40,3375310.0,9377.200,7027.860,30247.8,20845.1,267677.0,4153170.0,...,321649.0,19725.9,2221.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1559,42579_6,8407400.0,52880.70,5974080.0,23799.400,8683.810,95538.0,NaN,36968.0,3081480.0,...,432849.0,35454.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1668,47171_6,7950810.0,44828.80,6300490.0,19227.400,8739.100,25884.1,43060.8,31655.9,2996810.0,...,586442.0,51210.9,20206.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1697,48780_6,10575500.0,41773.40,10997400.0,44924.200,18465.400,63944.2,45118.1,518699.0,5285020.0,...,681990.0,60226.5,9453.53,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1751,49683_6,5238640.0,83889.90,5178680.0,50477.400,22546.600,157602.0,37141.1,47940.5,4422430.0,...,413413.0,15044.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1775,5027_6,3525890.0,44235.30,7515740.0,25630.600,15589.300,93523.8,48265.8,559630.0,5531080.0,...,706638.0,71468.7,18678.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1783,5036_6,3555830.0,44014.70,5494520.0,NaN,16463.400,51070.4,50432.9,253871.0,NaN,...,605613.0,73693.0,29885.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1850,5178_6,4908260.0,82431.30,12461100.0,19274.700,11158.900,88446.8,50045.3,541731.0,4358400.0,...,242514.0,63013.9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1933,54095_6,5772860.0,52362.60,7244590.0,NaN,15734.200,30240.4,43593.1,44804.6,3442030.0,...,515116.0,39400.8,9588.66,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1995,55302_6,9930640.0,51509.10,8215650.0,NaN,3068.010,96657.5,42664.1,565454.0,4850810.0,...,402431.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2147,57009_6,9780070.0,42045.50,6828890.0,28186.600,16007.700,51670.5,44248.3,64831.7,5388600.0,...,526330.0,61271.6,21069.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2196,57468_3,7121670.0,34249.20,9316990.0,NaN,21460.500,122868.0,40492.1,70598.0,7634860.0,...,423716.0,39336.0,14529.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2243,58270_6,7370460.0,65887.60,7916190.0,75041.600,13220.800,193527.0,58059.7,60658.3,4156350.0,...,479247.0,69482.2,20530.20,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2262,58648_6,NaN,25281.70,2953440.0,NaN,NaN,NaN,30490.6,23994.0,2538470.0,...,265703.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2286,58674_6,7576500.0,92782.30,5532510.0,33079.700,14901.600,63967.7,45207.0,50991.6,4974970.0,...,685363.0,63829.6,29559.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2333,60170_36,6829840.0,19263.90,14334200.0,12717.100,17450.000,NaN,38800.5,639639.0,8400960.0,...,425607.0,41613.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2345,60443_6,4284040.0,10789.90,NaN,23874.500,NaN,106065.0,10493.5,NaN,NaN,...,250434.0,NaN,30295.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2366,60788_6,11097000.0,33138.60,10571500.0,223.218,NaN,15570.8,31917.7,573346.0,6626060.0,...,446555.0,41500.7,13092.50,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2556,7117_6,7835520.0,35364.40,10351400.0,35759.200,NaN,53641.8,53233.0,428194.0,3761050.0,...,560694.0,44800.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2564,7151_6,10070200.0,48615.40,12968700.0,45380.900,17666.100,60536.1,56827.7,536613.0,7850160.0,...,644774.0,83132.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Because it is a time series dataset, we can study the effect of protein and peptide abundance on the updrs score in at a time point, but we can also study the effect of protein or peptide level changes on the change of updrs score in a time period for the later construction of a recurrent network.

To that end, we first split the combined table into several subtables by the month.

In [ ]:
# Observe that the smallest gap for any adjacent visit month is 3
def divisible_by_three(x) -> bool:
  return x%3==0
def divisible_by_six(x) -> bool:
  return x%6==0
display((~clinical_and_pivotted_peptides_and_protein_drop_untested['visit_month'].apply(divisible_by_three)).sum())
display((~clinical_and_pivotted_peptides_and_protein_drop_untested['visit_month'].apply(divisible_by_six)).sum())

np.int64(0)

np.int64(214)

Observe that the smallest gap is three, as all visit months are divisible by 3, but not all are divisible by 6.

The univariant analysis without imputation are conducted before, and to decide which imputation is appropriate, we need to do some bivariant or multivariant analysis.